class Region {
  final String name;
  final String code;
  final List<Gu>? gus; // 서울 등 3단계 지역만 사용
  final List<SubRegion>? subRegions; // 기존 방식(2단계)

  Region({
    required this.name,
    required this.code,
    this.gus,
    this.subRegions,
  });
}

class Gu {
  final String name;
  final String code;
  final List<SubRegion> dongs;

  Gu({
    required this.name,
    required this.code,
    required this.dongs,
  });
}

class SubRegion {
  final String name;
  final String code;

  SubRegion({
    required this.name,
    required this.code,
  });

  @override
  String toString() {
    return '$name-$code';
  }
}

// 지역 코드 데이터
class RegionData {
  static final List<Region> regions = [

    Region(
      name: '서울특별시',
      code: 'seoul',
      gus: [
        Gu(
          name: '강남구',
          code: 'gangnam',
          dongs: [
            SubRegion(name: '역삼동', code: '6035'),
            SubRegion(name: '청담동', code: '386'),
            SubRegion(name: '대치동', code: '6032'),
            SubRegion(name: '논현동', code: '6031'),
            SubRegion(name: '압구정동', code: '385'),
            SubRegion(name: '삼성동', code: '6034'),
            SubRegion(name: '신사동', code: '382'),
            SubRegion(name: '도곡동', code: '6033'),
            SubRegion(name: '개포동', code: '6030'),
            SubRegion(name: '일원동', code: '6037'),
            SubRegion(name: '자곡동', code: '6038'),
            SubRegion(name: '수서동', code: '403'),
            SubRegion(name: '세곡동', code: '399'),
            SubRegion(name: '율현동', code: '6036'),
          ],
        ),
        Gu(
          name: '강동구',
          code: 'gangdong',
          dongs: [
            SubRegion(name: '천호동', code: '6044'),
            SubRegion(name: '길동', code: '448'),
            SubRegion(name: '상일동', code: '434'),
            SubRegion(name: '성내동', code: '6042'),
            SubRegion(name: '강일동', code: '433'),
            SubRegion(name: '암사동', code: '6043'),
            SubRegion(name: '둔촌동', code: '6040'),
            SubRegion(name: '명일동', code: '6041'),
            SubRegion(name: '고덕동', code: '6039'),
          ],
        ),
        Gu(
          name: '강북구',
          code: 'gangbuk',
          dongs: [
            SubRegion(name: '미아동', code: '142'),
            SubRegion(name: '수유동', code: '6046'),
            SubRegion(name: '삼각산동', code: '145'),
            SubRegion(name: '삼양동', code: '141'),
            SubRegion(name: '번동', code: '6045'),
            SubRegion(name: '송중동', code: '143'),
            SubRegion(name: '인수동', code: '153'),
            SubRegion(name: '송천동', code: '144'),
            SubRegion(name: '우이동', code: '152'),
          ],
        ),
        Gu(
          name: '노원구',
          code: 'nowon',
          dongs: [
            SubRegion(name: '상계동', code: '6073'),
            SubRegion(name: '공릉동', code: '6072'),
            SubRegion(name: '중계동', code: '6075'),
            SubRegion(name: '월계동', code: '6074'),
            SubRegion(name: '하계동', code: '6076'),
          ],
        ),
        Gu(
          name: '성북구',
          code: 'seongbuk',
          dongs: [
            SubRegion(name: '종암동', code: '133'),
            SubRegion(name: '길음동', code: '6145'),
            SubRegion(name: '석관동', code: '139'),
            SubRegion(name: '장위동', code: '6178'),
            SubRegion(name: '하월곡동', code: '6180'),
            SubRegion(name: '정릉동', code: '6179'),
            SubRegion(name: '돈암동', code: '6146'),
            SubRegion(name: '안암동', code: '125'),
            SubRegion(name: '성북동', code: '120'),
            SubRegion(name: '상월곡동', code: '6171'),
            SubRegion(name: '동선동', code: '122'),
            SubRegion(name: '삼선동', code: '121'),
            SubRegion(name: '보문동', code: '126'),
          ],
        ),
        Gu(
          name: '동대문구',
          code: 'dongdaemun',
          dongs: [
            SubRegion(name: '장안동', code: '6085'),
            SubRegion(name: '이문동', code: '6084'),
            SubRegion(name: '답십리동', code: '6081'),
            SubRegion(name: '휘경동', code: '6087'),
            SubRegion(name: '전농동', code: '6086'),
            SubRegion(name: '제기동', code: '89'),
            SubRegion(name: '용두동', code: '6083'),
            SubRegion(name: '회기동', code: '97'),
            SubRegion(name: '청량리동', code: '96'),
            SubRegion(name: '신설동', code: '6082'),
            SubRegion(name: '용신동', code: '88'),
          ],
        ),
        Gu(
          name: '중랑구',
          code: 'jungnang',
          dongs: [
            SubRegion(name: '면목동', code: '6407'),
            SubRegion(name: '상봉동', code: '6409'),
            SubRegion(name: '묵동', code: '6408'),
            SubRegion(name: '신내동', code: '6410'),
            SubRegion(name: '중화동', code: '6411'),
            SubRegion(name: '망우동', code: '6406'),
            SubRegion(name: '면목본동', code: '106'),
            SubRegion(name: '망우본동', code: '115'),
          ],
        ),
        Gu(
          name: '광진구',
          code: 'gwangjin',
          dongs: [
            SubRegion(name: '화양동', code: '72'),
            SubRegion(name: '자양동', code: '6060'),
            SubRegion(name: '구의동', code: '6059'),
            SubRegion(name: '광장동', code: '79'),
            SubRegion(name: '중곡동', code: '6061'),
            SubRegion(name: '군자동', code: '73'),
            SubRegion(name: '능동', code: '78'),
          ],
        ),
      ],
    ),
    Region(
      name: '경기도',
      code: 'gyeonggi',
      gus: [
        Gu(
          name: '선택 안함 (전체 구)',
          code: 'all',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
          ],
        ),
        Gu(
          name: '성남시',
          code: 'seongnam',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '정자동', code: '1339'),
            SubRegion(name: '삼평동', code: '1351'),
            SubRegion(name: '백현동', code: '1352'),
            SubRegion(name: '구미동', code: '1355'),
            SubRegion(name: '판교동', code: '1350'),
            SubRegion(name: '서현동', code: '4502'),
            SubRegion(name: '금곡동', code: '1353'),
            SubRegion(name: '야탑동', code: '4505'),
            SubRegion(name: '분당동', code: '1335'),
            SubRegion(name: '운중동', code: '1356'),
            SubRegion(name: '이매동', code: '4507'),
            SubRegion(name: '수내동', code: '4504'),
            SubRegion(name: '대장동', code: '4500'),
            SubRegion(name: '궁내동', code: '4499'),
            SubRegion(name: '율동', code: '4506'),
            SubRegion(name: '석운동', code: '4503'),
            SubRegion(name: '하산운동', code: '4508'),
            SubRegion(name: '동원동', code: '4501'),
            SubRegion(name: '성남동', code: '1323'),
            SubRegion(name: '하대원동', code: '1332'),
            SubRegion(name: '금광동', code: '4520'),
            SubRegion(name: '중앙동', code: '1324'),
            SubRegion(name: '도촌동', code: '1333'),
            SubRegion(name: '상대원동', code: '4521'),
            SubRegion(name: '은행동', code: '4523'),
            SubRegion(name: '여수동', code: '4522'),
            SubRegion(name: '갈현동', code: '4519'),
            SubRegion(name: '위례동', code: '3971'),
            SubRegion(name: '창곡동', code: '4517'),
            SubRegion(name: '태평동', code: '4518'),
            SubRegion(name: '신흥동', code: '4514'),
            SubRegion(name: '복정동', code: '1318'),
            SubRegion(name: '단대동', code: '1315'),
            SubRegion(name: '양지동', code: '1317'),
            SubRegion(name: '고등동', code: '1320'),
            SubRegion(name: '시흥동', code: '1321'),
            SubRegion(name: '산성동', code: '1316'),
            SubRegion(name: '신촌동', code: '1319'),
            SubRegion(name: '수진동', code: '4513'),
            SubRegion(name: '심곡동', code: '4515'),
            SubRegion(name: '금토동', code: '4509'),
            SubRegion(name: '사송동', code: '4511'),
            SubRegion(name: '상적동', code: '4512'),
            SubRegion(name: '오야동', code: '4516'),
            SubRegion(name: '둔전동', code: '4510'),
          ],
        ),
        Gu(
          name: '남양주시',
          code: 'namyangju',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '인창동', code: '1581'),
            SubRegion(name: '갈매동', code: '1579'),
            SubRegion(name: '수택동', code: '4455'),
            SubRegion(name: '교문동', code: '4453'),
            SubRegion(name: '토평동', code: '4457'),
            SubRegion(name: '동구동', code: '1580'),
            SubRegion(name: '아천동', code: '4456'),
            SubRegion(name: '사노동', code: '4454'),
            SubRegion(name: '화도읍', code: '1590'),
            SubRegion(name: '진접읍', code: '1589'),
            SubRegion(name: '별내동', code: '1604'),
            SubRegion(name: '다산동', code: '4470'),
            SubRegion(name: '호평동', code: '1598'),
            SubRegion(name: '와부읍', code: '1588'),
            SubRegion(name: '오남읍', code: '1593'),
            SubRegion(name: '평내동', code: '1599'),
            SubRegion(name: '퇴계원읍', code: '1597'),
            SubRegion(name: '진건읍', code: '1592'),
            SubRegion(name: '금곡동', code: '1600'),
            SubRegion(name: '별내면', code: '1594'),
            SubRegion(name: '수동면', code: '1595'),
            SubRegion(name: '도농동', code: '4471'),
            SubRegion(name: '조안면', code: '1596'),
            SubRegion(name: '일패동', code: '4475'),
            SubRegion(name: '지금동', code: '4476'),
            SubRegion(name: '삼패동', code: '4472'),
            SubRegion(name: '양정동', code: '1601'),
            SubRegion(name: '수석동', code: '4473'),
            SubRegion(name: '이패동', code: '4474'),
          ],
        ),
        Gu(
          name: '광명시',
          code: 'gwangmyeong',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '일직동', code: '4440'),
            SubRegion(name: '철산동', code: '4441'),
            SubRegion(name: '소하동', code: '4438'),
            SubRegion(name: '하안동', code: '4442'),
            SubRegion(name: '광명동', code: '4436'),
            SubRegion(name: '노온사동', code: '4437'),
            SubRegion(name: '가학동', code: '4435'),
            SubRegion(name: '옥길동', code: '4439'),
            SubRegion(name: '학온동', code: '1465'),
          ],
        ),
        Gu(
          name: '하남시',
          code: 'hanam',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '망월동', code: '4814'),
            SubRegion(name: '덕풍동', code: '4813'),
            SubRegion(name: '풍산동', code: '1657'),
            SubRegion(name: '신장동', code: '4820'),
            SubRegion(name: '미사동', code: '4815'),
            SubRegion(name: '감이동', code: '4808'),
            SubRegion(name: '위례동', code: '3965'),
            SubRegion(name: '감일동', code: '4809'),
            SubRegion(name: '학암동', code: '4825'),
            SubRegion(name: '창우동', code: '4821'),
            SubRegion(name: '선동', code: '4819'),
            SubRegion(name: '감북동', code: '1658'),
            SubRegion(name: '천현동', code: '1651'),
            SubRegion(name: '초이동', code: '1660'),
            SubRegion(name: '하산곡동', code: '4824'),
            SubRegion(name: '초일동', code: '4822'),
            SubRegion(name: '춘궁동', code: '1659'),
            SubRegion(name: '상산곡동', code: '4818'),
            SubRegion(name: '광암동', code: '4810'),
            SubRegion(name: '교산동', code: '4811'),
            SubRegion(name: '하사창동', code: '4823'),
            SubRegion(name: '상사창동', code: '4817'),
            SubRegion(name: '항동', code: '4826'),
            SubRegion(name: '배알미동', code: '4816'),
            SubRegion(name: '당정동', code: '4812'),
          ],
        ),
        Gu(
          name: '평택시',
          code: 'pyeongtaek',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '고덕동', code: '11139'),
            SubRegion(name: '비전동', code: '4786'),
            SubRegion(name: '안중읍', code: '1468'),
            SubRegion(name: '동삭동', code: '4784'),
            SubRegion(name: '서정동', code: '1477'),
            SubRegion(name: '용이동', code: '4790'),
            SubRegion(name: '포승읍', code: '1469'),
            SubRegion(name: '세교동', code: '1488'),
            SubRegion(name: '팽성읍', code: '1467'),
            SubRegion(name: '청북읍', code: '1474'),
            SubRegion(name: '지산동', code: '1479'),
            SubRegion(name: '이충동', code: '4793'),
            SubRegion(name: '고덕면', code: '1472'),
            SubRegion(name: '합정동', code: '4802'),
            SubRegion(name: '평택동', code: '4801'),
            SubRegion(name: '죽백동', code: '4796'),
            SubRegion(name: '칠원동', code: '4800'),
            SubRegion(name: '소사동', code: '4787'),
            SubRegion(name: '신장동', code: '4789'),
            SubRegion(name: '장당동', code: '4794'),
            SubRegion(name: '진위면', code: '1470'),
            SubRegion(name: '중앙동', code: '1476'),
            SubRegion(name: '지제동', code: '4797'),
            SubRegion(name: '통복동', code: '1485'),
            SubRegion(name: '원평동', code: '1484'),
            SubRegion(name: '송북동', code: '1480'),
            SubRegion(name: '오성면', code: '1473'),
            SubRegion(name: '장안동', code: '4795'),
            SubRegion(name: '독곡동', code: '4783'),
            SubRegion(name: '서탄면', code: '1471'),
            SubRegion(name: '신평동', code: '1483'),
            SubRegion(name: '송탄동', code: '1478'),
            SubRegion(name: '현덕면', code: '1475'),
            SubRegion(name: '가재동', code: '4780'),
            SubRegion(name: '군문동', code: '4781'),
            SubRegion(name: '칠괴동', code: '4799'),
            SubRegion(name: '신대동', code: '4788'),
            SubRegion(name: '모곡동', code: '4785'),
            SubRegion(name: '도일동', code: '4782'),
            SubRegion(name: '유천동', code: '4792'),
            SubRegion(name: '월곡동', code: '4791'),
            SubRegion(name: '청룡동', code: '4798'),
          ],
        ),
        Gu(
          name: '용인시',
          code: 'yongin',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            // 수지구
            SubRegion(name: '성복동', code: '1697'),
            SubRegion(name: '동천동', code: '1694'),
            SubRegion(name: '죽전동', code: '4719'),
            SubRegion(name: '상현동', code: '4718'),
            SubRegion(name: '신봉동', code: '1691'),
            SubRegion(name: '풍덕천동', code: '4720'),
            SubRegion(name: '풍덕천2동', code: '1690'),
            SubRegion(name: '죽전1동', code: '1692'),
            SubRegion(name: '풍덕천1동', code: '1689'),
            SubRegion(name: '죽전2동', code: '1693'),
            SubRegion(name: '상현2동', code: '1696'),
            SubRegion(name: '상현1동', code: '1695'),
            SubRegion(name: '상현3동', code: '11469'),
            SubRegion(name: '죽전3동', code: '11470'),
            SubRegion(name: '고기동', code: '4717'),
            // 기흥구
            SubRegion(name: '구갈동', code: '1679'),
            SubRegion(name: '동백동', code: '1685'),
            SubRegion(name: '중동', code: '4713'),
            SubRegion(name: '신갈동', code: '1677'),
            SubRegion(name: '보정동', code: '1687'),
            SubRegion(name: '영덕동', code: '1678'),
            SubRegion(name: '마북동', code: '1684'),
            SubRegion(name: '보라동', code: '4710'),
            SubRegion(name: '상하동', code: '1686'),
            SubRegion(name: '서천동', code: '4711'),
            SubRegion(name: '언남동', code: '4712'),
            SubRegion(name: '상갈동', code: '1680'),
            SubRegion(name: '공세동', code: '4708'),
            SubRegion(name: '청덕동', code: '4715'),
            SubRegion(name: '구성동', code: '1683'),
            SubRegion(name: '영덕1동', code: '11304'),
            SubRegion(name: '영덕2동', code: '11305'),
            SubRegion(name: '고매동', code: '4707'),
            SubRegion(name: '서농동', code: '1682'),
            SubRegion(name: '기흥동', code: '1681'),
            SubRegion(name: '하갈동', code: '4716'),
            SubRegion(name: '지곡동', code: '4714'),
            SubRegion(name: '농서동', code: '4709'),
            // 처인구
            SubRegion(name: '역북동', code: '4726'),
            SubRegion(name: '포곡읍', code: '1665'),
            SubRegion(name: '모현읍', code: '1666'),
            SubRegion(name: '김량장동', code: '4722'),
            SubRegion(name: '고림동', code: '4721'),
            SubRegion(name: '남사읍', code: '1667'),
            SubRegion(name: '양지면', code: '1671'),
            SubRegion(name: '이동읍', code: '1668'),
            SubRegion(name: '유림동', code: '1674'),
            SubRegion(name: '삼가동', code: '4725'),
            SubRegion(name: '마평동', code: '4724'),
            SubRegion(name: '중앙동', code: '1672'),
            SubRegion(name: '유방동', code: '4728'),
            SubRegion(name: '역삼동', code: '1673'),
            SubRegion(name: '백암면', code: '1670'),
            SubRegion(name: '원삼면', code: '1669'),
            SubRegion(name: '남동', code: '4723'),
            SubRegion(name: '운학동', code: '4727'),
            SubRegion(name: '호동', code: '4730'),
            SubRegion(name: '해곡동', code: '4729'),
          ],
        ),
      ],
    ),
    Region(
      name: '인천광역시',
      code: 'incheon',
      subRegions: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
        SubRegion(name: '구월동', code: '6496'),
        SubRegion(name: '논현동', code: '6498'),
        SubRegion(name: '간석동', code: '6494'),
        SubRegion(name: '만수동', code: '6500'),
        SubRegion(name: '서창동', code: '6501'),
        SubRegion(name: '논현고잔동', code: '909'),
        SubRegion(name: '고잔동', code: '6495'),
        SubRegion(name: '남촌동', code: '6497'),
        SubRegion(name: '도림동', code: '6499'),
        SubRegion(name: '남촌도림동', code: '906'),
        SubRegion(name: '장수동', code: '6504'),
        SubRegion(name: '수산동', code: '6502'),
        SubRegion(name: '운연동', code: '6503'),
        SubRegion(name: '작전동', code: '6489'),
        SubRegion(name: '계산동', code: '6472'),
        SubRegion(name: '작전서운동', code: '942'),
        SubRegion(name: '효성동', code: '6493'),
        SubRegion(name: '병방동', code: '6481'),
        SubRegion(name: '임학동', code: '6488'),
        SubRegion(name: '동양동', code: '6476'),
        SubRegion(name: '용종동', code: '6486'),
        SubRegion(name: '박촌동', code: '6479'),
        SubRegion(name: '귤현동', code: '6473'),
        SubRegion(name: '서운동', code: '6483'),
        SubRegion(name: '방축동', code: '6480'),
        SubRegion(name: '오류동', code: '6485'),
        SubRegion(name: '이화동', code: '6487'),
        SubRegion(name: '다남동', code: '6475'),
        SubRegion(name: '하야동', code: '6492'),
        SubRegion(name: '갈현동', code: '6471'),
        SubRegion(name: '상야동', code: '6482'),
        SubRegion(name: '둑실동', code: '6477'),
        SubRegion(name: '평동', code: '6491'),
        SubRegion(name: '선주지동', code: '6484'),
        SubRegion(name: '목상동', code: '6478'),
        SubRegion(name: '노오지동', code: '6474'),
        SubRegion(name: '강화읍', code: '969'),
        SubRegion(name: '선원면', code: '970'),
        SubRegion(name: '길상면', code: '972'),
        SubRegion(name: '불은면', code: '971'),
        SubRegion(name: '양도면', code: '974'),
        SubRegion(name: '화도면', code: '973'),
        SubRegion(name: '하점면', code: '976'),
        SubRegion(name: '송해면', code: '978'),
        SubRegion(name: '내가면', code: '975'),
        SubRegion(name: '삼산면', code: '980'),
        SubRegion(name: '양사면', code: '977'),
        SubRegion(name: '교동면', code: '979'),
        SubRegion(name: '서도면', code: '981'),
        SubRegion(name: '송림동', code: '6506'),
        SubRegion(name: '송현동', code: '6507'),
        SubRegion(name: '만석동', code: '843'),
        SubRegion(name: '화수동', code: '6509'),
        SubRegion(name: '창영동', code: '6508'),
        SubRegion(name: '금곡동', code: '6505'),
        SubRegion(name: '화평동', code: '6510'),
        SubRegion(name: '도화동', code: '865'),
        SubRegion(name: '관교동', code: '874'),
      ],
    ),
    Region(
      name: '충청북도',
      code: 'chungbuk',
      gus: [
        Gu(
          name: '선택 안함 (전체 구)',
          code: 'all',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
          ],
        ),
        Gu(
          name: '제천시',
          code: 'jecheon',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '장락동', code: '7146'),
            SubRegion(name: '청전동', code: '2183'),
            SubRegion(name: '하소동', code: '7150'),
            SubRegion(name: '강제동', code: '7128'),
            SubRegion(name: '신백동', code: '2182'),
            SubRegion(name: '화산동', code: '2184'),
            SubRegion(name: '고암동', code: '7130'),
            SubRegion(name: '신월동', code: '7141'),
            SubRegion(name: '봉양읍', code: '2168'),
            SubRegion(name: '영천동', code: '7142'),
            SubRegion(name: '왕암동', code: '7143'),
            SubRegion(name: '용두동', code: '2181'),
            SubRegion(name: '의림지동', code: '4162'),
            SubRegion(name: '의림동', code: '7144'),
            SubRegion(name: '송학면', code: '2175'),
            SubRegion(name: '중앙동', code: '4161'),
            SubRegion(name: '천남동', code: '7149'),
            SubRegion(name: '중앙로2가', code: '7148'),
            SubRegion(name: '남현동', code: '2179'),
            SubRegion(name: '서부동', code: '7139'),
            SubRegion(name: '동현동', code: '7133'),
            SubRegion(name: '명동', code: '7135'),
            SubRegion(name: '교동', code: '2176'),
            SubRegion(name: '남천동', code: '7131'),
            SubRegion(name: '영서동', code: '2180'),
            SubRegion(name: '백운면', code: '2174'),
            SubRegion(name: '모산동', code: '7137'),
            SubRegion(name: '중앙로1가', code: '7147'),
            SubRegion(name: '수산면', code: '2171'),
            SubRegion(name: '청풍면', code: '2170'),
            SubRegion(name: '금성면', code: '2169'),
            SubRegion(name: '덕산면', code: '2172'),
            SubRegion(name: '한수면', code: '2173'),
            SubRegion(name: '고명동', code: '7129'),
            SubRegion(name: '두학동', code: '7134'),
            SubRegion(name: '흑석동', code: '7151'),
            SubRegion(name: '명지동', code: '7136'),
            SubRegion(name: '산곡동', code: '7138'),
            SubRegion(name: '신동', code: '7140'),
            SubRegion(name: '자작동', code: '7145'),
            SubRegion(name: '대랑동', code: '7132'),
          ],
        ),
        Gu(
          name: '음성군',
          code: 'eumseong',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '금왕읍', code: '2244'),
            SubRegion(name: '대소면', code: '2248'),
            SubRegion(name: '맹동면', code: '2247'),
            SubRegion(name: '음성읍', code: '2243'),
            SubRegion(name: '감곡면', code: '2251'),
            SubRegion(name: '삼성면', code: '2249'),
            SubRegion(name: '생극면', code: '2250'),
            SubRegion(name: '원남면', code: '2246'),
            SubRegion(name: '소이면', code: '2245'),
          ],
        ),
        Gu(
          name: '옥천군',
          code: 'okcheon',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '옥천읍', code: '2198'),
            SubRegion(name: '이원면', code: '2204'),
            SubRegion(name: '동이면', code: '2199'),
            SubRegion(name: '군북면', code: '2206'),
            SubRegion(name: '청산면', code: '2203'),
            SubRegion(name: '군서면', code: '2205'),
            SubRegion(name: '청성면', code: '2202'),
            SubRegion(name: '안내면', code: '2201'),
            SubRegion(name: '안남면', code: '2200'),
          ],
        ),
        Gu(
          name: '영동군',
          code: 'yeongdong',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '영동읍', code: '2208'),
            SubRegion(name: '황간면', code: '2210'),
            SubRegion(name: '용산면', code: '2209'),
            SubRegion(name: '추풍령면', code: '2211'),
            SubRegion(name: '상촌면', code: '2213'),
            SubRegion(name: '양강면', code: '2214'),
            SubRegion(name: '학산면', code: '2216'),
            SubRegion(name: '심천면', code: '2218'),
            SubRegion(name: '매곡면', code: '2212'),
            SubRegion(name: '양산면', code: '2217'),
            SubRegion(name: '용화면', code: '2215'),
          ],
        ),
        Gu(
          name: '괴산군',
          code: 'goesan',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '괴산읍', code: '2231'),
            SubRegion(name: '청천면', code: '2237'),
            SubRegion(name: '칠성면', code: '2235'),
            SubRegion(name: '청안면', code: '2238'),
            SubRegion(name: '사리면', code: '2239'),
            SubRegion(name: '불정면', code: '2241'),
            SubRegion(name: '소수면', code: '2240'),
            SubRegion(name: '문광면', code: '2236'),
            SubRegion(name: '연풍면', code: '2234'),
            SubRegion(name: '감물면', code: '2232'),
            SubRegion(name: '장연면', code: '2233'),
          ],
        ),
        Gu(
          name: '단양군',
          code: 'danyang',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '단양읍', code: '2253'),
            SubRegion(name: '매포읍', code: '2254'),
            SubRegion(name: '영춘면', code: '2257'),
            SubRegion(name: '대강면', code: '2255'),
            SubRegion(name: '가곡면', code: '2256'),
            SubRegion(name: '어상천면', code: '2258'),
            SubRegion(name: '적성면', code: '2259'),
            SubRegion(name: '단성면', code: '2260'),
          ],
        ),
        Gu(
          name: '보은군',
          code: 'boeun',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '보은읍', code: '2186'),
            SubRegion(name: '삼승면', code: '2191'),
            SubRegion(name: '마로면', code: '2189'),
            SubRegion(name: '속리산면', code: '2187'),
            SubRegion(name: '탄부면', code: '2190'),
            SubRegion(name: '회인면', code: '2194'),
            SubRegion(name: '내북면', code: '2195'),
            SubRegion(name: '산외면', code: '2196'),
            SubRegion(name: '수한면', code: '2192'),
            SubRegion(name: '장안면', code: '2188'),
            SubRegion(name: '회남면', code: '2193'),
          ],
        ),
      ],
    ),
    Region(
      name: '충청남도',
      code: 'chungnam',
      gus: [
        Gu(
          name: '당진시',
          code: 'dangjin',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '송악읍', code: '2388'),
            SubRegion(name: '읍내동', code: '7057'),
            SubRegion(name: '수청동', code: '7052'),
            SubRegion(name: '송산면', code: '2397'),
            SubRegion(name: '신평면', code: '2396'),
            SubRegion(name: '당진1동', code: '2398'),
            SubRegion(name: '채운동', code: '7058'),
            SubRegion(name: '합덕읍', code: '2387'),
            SubRegion(name: '석문면', code: '2390'),
            SubRegion(name: '원당동', code: '7056'),
            SubRegion(name: '당진3동', code: '2400'),
            SubRegion(name: '대덕동', code: '7050'),
            SubRegion(name: '당진2동', code: '2399'),
            SubRegion(name: '고대면', code: '2389'),
            SubRegion(name: '순성면', code: '2394'),
            SubRegion(name: '우강면', code: '2395'),
            SubRegion(name: '정미면', code: '2392'),
            SubRegion(name: '우두동', code: '7055'),
            SubRegion(name: '시곡동', code: '7053'),
            SubRegion(name: '용연동', code: '7054'),
            SubRegion(name: '구룡동', code: '7049'),
            SubRegion(name: '사기소동', code: '7051'),
            SubRegion(name: '행정동', code: '7059'),
          ],
        ),
        Gu(
          name: '공주시',
          code: 'gongju',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '신관동', code: '2310'),
            SubRegion(name: '금흥동', code: '7022'),
            SubRegion(name: '월송동', code: '2311'),
            SubRegion(name: '옥룡동', code: '2309'),
            SubRegion(name: '금학동', code: '2308'),
            SubRegion(name: '유구읍', code: '2296'),
            SubRegion(name: '의당면', code: '2301'),
            SubRegion(name: '반포면', code: '2300'),
            SubRegion(name: '웅진동', code: '2307'),
            SubRegion(name: '계룡면', code: '2299'),
            SubRegion(name: '우성면', code: '2303'),
            SubRegion(name: '정안면', code: '2302'),
            SubRegion(name: '사곡면', code: '2304'),
            SubRegion(name: '신풍면', code: '2305'),
            SubRegion(name: '반죽동', code: '7025'),
            SubRegion(name: '석장리동', code: '7030'),
            SubRegion(name: '송선동', code: '7032'),
            SubRegion(name: '쌍신동', code: '7034'),
            SubRegion(name: '소학동', code: '7031'),
            SubRegion(name: '검상동', code: '7019'),
            SubRegion(name: '월미동', code: '7036'),
            SubRegion(name: '봉정동', code: '7026'),
            SubRegion(name: '상왕동', code: '7029'),
            SubRegion(name: '동현동', code: '7023'),
            SubRegion(name: '신기동', code: '7033'),
            SubRegion(name: '오곡동', code: '7035'),
            SubRegion(name: '태봉동', code: '7039'),
            SubRegion(name: '주미동', code: '7037'),
            SubRegion(name: '무릉동', code: '7024'),
            SubRegion(name: '교동', code: '7020'),
            SubRegion(name: '중동', code: '7038'),
            SubRegion(name: '금성동', code: '7021'),
            SubRegion(name: '산성동', code: '7028'),
            SubRegion(name: '봉황동', code: '7027'),
            SubRegion(name: '중학동', code: '2306'),
            SubRegion(name: '이인면', code: '2297'),
            SubRegion(name: '탄천면', code: '2298'),
          ],
        ),
        Gu(
          name: '논산시',
          code: 'nonsan',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '취암동', code: '2379'),
            SubRegion(name: '내동', code: '7042'),
            SubRegion(name: '연무읍', code: '2367'),
            SubRegion(name: '부창동', code: '2380'),
            SubRegion(name: '강산동', code: '7040'),
            SubRegion(name: '대교동', code: '7043'),
            SubRegion(name: '연산면', code: '2373'),
            SubRegion(name: '은진면', code: '2377'),
            SubRegion(name: '양촌면', code: '2375'),
            SubRegion(name: '화지동', code: '7048'),
            SubRegion(name: '반월동', code: '7046'),
            SubRegion(name: '관촉동', code: '7041'),
            SubRegion(name: '지산동', code: '7047'),
            SubRegion(name: '등화동', code: '7045'),
            SubRegion(name: '덕지동', code: '7044'),
            SubRegion(name: '강경읍', code: '2366'),
            SubRegion(name: '부적면', code: '2372'),
            SubRegion(name: '성동면', code: '2368'),
            SubRegion(name: '광석면', code: '2369'),
            SubRegion(name: '상월면', code: '2371'),
            SubRegion(name: '가야곡면', code: '2376'),
            SubRegion(name: '노성면', code: '2370'),
            SubRegion(name: '벌곡면', code: '2374'),
            SubRegion(name: '채운면', code: '2378'),
          ],
        ),
        Gu(
          name: '계룡시',
          code: 'gyeryong',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '엄사면', code: '2383'),
            SubRegion(name: '금암동', code: '2385'),
            SubRegion(name: '두마면', code: '2382'),
            SubRegion(name: '신도안면', code: '2384'),
          ],
        ),
        Gu(
          name: '금산군',
          code: 'geumsan',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '금산읍', code: '2402'),
            SubRegion(name: '추부면', code: '2411'),
            SubRegion(name: '금성면', code: '2403'),
            SubRegion(name: '제원면', code: '2404'),
            SubRegion(name: '복수면', code: '2410'),
            SubRegion(name: '진산면', code: '2409'),
            SubRegion(name: '군북면', code: '2406'),
            SubRegion(name: '부리면', code: '2405'),
            SubRegion(name: '남일면', code: '2407'),
            SubRegion(name: '남이면', code: '2408'),
          ],
        ),
      ],
    ),
    Region(
      name: '대전광역시',
      code: 'daejeon',
      gus: [
        Gu(
          name: '동구',
          code: 'donggu',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '용전동', code: '1106'),
            SubRegion(name: '용운동', code: '1101'),
            SubRegion(name: '자양동', code: '1103'),
            SubRegion(name: '가오동', code: '5752'),
            SubRegion(name: '가양동', code: '5751'),
            SubRegion(name: '홍도동', code: '1108'),
            SubRegion(name: '대동', code: '1102'),
            SubRegion(name: '삼성동', code: '1109'),
            SubRegion(name: '천동', code: '5783'),
            SubRegion(name: '성남동', code: '1107'),
            SubRegion(name: '가양2동', code: '1105'),
            SubRegion(name: '가양1동', code: '1104'),
            SubRegion(name: '판암동', code: '5785'),
            SubRegion(name: '판암1동', code: '1099'),
            SubRegion(name: '낭월동', code: '5754'),
            SubRegion(name: '효동', code: '1097'),
            SubRegion(name: '판암2동', code: '1100'),
            SubRegion(name: '소제동', code: '5765'),
            SubRegion(name: '대성동', code: '5757'),
            SubRegion(name: '산내동', code: '1111'),
            SubRegion(name: '신흥동', code: '5771'),
            SubRegion(name: '중동', code: '5781'),
            SubRegion(name: '정동', code: '5778'),
            SubRegion(name: '원동', code: '5774'),
            SubRegion(name: '인동', code: '5776'),
            SubRegion(name: '신인동', code: '1098'),
            SubRegion(name: '구도동', code: '5753'),
            SubRegion(name: '대청동', code: '1110'),
            SubRegion(name: '세천동', code: '5764'),
            SubRegion(name: '상소동', code: '5763'),
            SubRegion(name: '삼정동', code: '5762'),
            SubRegion(name: '추동', code: '5784'),
            SubRegion(name: '이사동', code: '5775'),
            SubRegion(name: '비룡동', code: '5759'),
            SubRegion(name: '신상동', code: '5767'),
            SubRegion(name: '신하동', code: '5770'),
            SubRegion(name: '주산동', code: '5779'),
            SubRegion(name: '직동', code: '5782'),
            SubRegion(name: '소호동', code: '5766'),
            SubRegion(name: '신촌동', code: '5769'),
            SubRegion(name: '주촌동', code: '5780'),
            SubRegion(name: '오동', code: '5772'),
            SubRegion(name: '장척동', code: '5777'),
            SubRegion(name: '효평동', code: '5787'),
            SubRegion(name: '내탑동', code: '5755'),
            SubRegion(name: '마산동', code: '5758'),
            SubRegion(name: '사성동', code: '5760'),
          ],
        ),
        Gu(
          name: '서구',
          code: 'seogu',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '관저동', code: '5789'),
            SubRegion(name: '갈마동', code: '5788'),
            SubRegion(name: '관저2동', code: '1148'),
            SubRegion(name: '갈마2동', code: '1142'),
            SubRegion(name: '관저1동', code: '1147'),
            SubRegion(name: '갈마1동', code: '1141'),
            SubRegion(name: '가수원동', code: '1146'),
            SubRegion(name: '가장동', code: '1139'),
            SubRegion(name: '괴곡동', code: '5790'),
          ],
        ),
        Gu(
          name: '대덕구',
          code: 'daedeokgu',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '송촌동', code: '1171'),
            SubRegion(name: '중리동', code: '1172'),
            SubRegion(name: '오정동', code: '1167'),
            SubRegion(name: '신탄진동', code: '1173'),
            SubRegion(name: '비래동', code: '1170'),
            SubRegion(name: '석봉동', code: '1174'),
            SubRegion(name: '법2동', code: '1178'),
            SubRegion(name: '덕암동', code: '1175'),
            SubRegion(name: '법1동', code: '1177'),
            SubRegion(name: '법동', code: '5737'),
            SubRegion(name: '대화동', code: '1168'),
            SubRegion(name: '읍내동', code: '5746'),
            SubRegion(name: '와동', code: '5744'),
            SubRegion(name: '상서동', code: '5740'),
            SubRegion(name: '신일동', code: '5742'),
            SubRegion(name: '연축동', code: '5743'),
            SubRegion(name: '평촌동', code: '5749'),
            SubRegion(name: '장동', code: '5748'),
            SubRegion(name: '목상동', code: '1176'),
            SubRegion(name: '미호동', code: '5736'),
            SubRegion(name: '용호동', code: '5745'),
            SubRegion(name: '삼정동', code: '5739'),
            SubRegion(name: '부수동', code: '5738'),
            SubRegion(name: '갈전동', code: '5734'),
            SubRegion(name: '회덕동', code: '1169'),
            SubRegion(name: '황호동', code: '5750'),
          ],
        ),
      ],
    ),
    Region(
      name: '대구광역시',
      code: 'daegu',
      gus: [
        Gu(
          name: '선택 안함 (전체 구)',
          code: 'all',
          dongs: [SubRegion(name: '선택 안함 (전체 동)', code: 'all')],
        ),
        Gu(
          name: '달서구',
          code: 'dalseo',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '월성동', code: '5572'),
            SubRegion(name: '감삼동', code: '794'),
            SubRegion(name: '진천동', code: '805'),
            SubRegion(name: '도원동', code: '809'),
            SubRegion(name: '신당동', code: '801'),
            SubRegion(name: '이곡동', code: '5575'),
            SubRegion(name: '본리동', code: '802'),
            SubRegion(name: '용산동', code: '5571'),
            SubRegion(name: '유천동', code: '5574'),
            SubRegion(name: '상인동', code: '5569'),
            SubRegion(name: '상인1동', code: '806'),
            SubRegion(name: '성당동', code: '791'),
            SubRegion(name: '이곡1동', code: '799'),
            SubRegion(name: '두류1.2동', code: '792'),
            SubRegion(name: '송현1동', code: '810'),
            SubRegion(name: '송현2동', code: '811'),
            SubRegion(name: '본동', code: '812'),
            SubRegion(name: '월성1동', code: '803'),
            SubRegion(name: '월성2동', code: '804'),
            SubRegion(name: '이곡2동', code: '800'),
            SubRegion(name: '상인2동', code: '807'),
            SubRegion(name: '상인3동', code: '808'),
            SubRegion(name: '두류3동', code: '793'),
            SubRegion(name: '장기동', code: '796'),
            SubRegion(name: '죽전동', code: '795'),
            SubRegion(name: '용산1동', code: '797'),
            SubRegion(name: '용산2동', code: '798'),
            SubRegion(name: '송현동', code: '5570'),
            SubRegion(name: '대곡동', code: '5566'),
            SubRegion(name: '장동', code: '5576'),
            SubRegion(name: '호림동', code: '5578'),
            SubRegion(name: '파호동', code: '5577'),
            SubRegion(name: '월암동', code: '5573'),
            SubRegion(name: '갈산동', code: '5565'),
            SubRegion(name: '대천동', code: '5567'),
            SubRegion(name: '두류동', code: '5568'),
            SubRegion(name: '호산동', code: '5579'),
          ],
        ),
        Gu(
          name: '달성군',
          code: 'dalseong',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '다사읍', code: '817'),
            SubRegion(name: '화원읍', code: '814'),
            SubRegion(name: '유가읍', code: '823'),
            SubRegion(name: '현풍읍', code: '822'),
            SubRegion(name: '구지면', code: '824'),
            SubRegion(name: '논공읍', code: '815'),
            SubRegion(name: '옥포읍', code: '821'),
            SubRegion(name: '가창면', code: '819'),
            SubRegion(name: '하빈면', code: '820'),
          ],
        ),
        Gu(
          name: '동구',
          code: 'donggu',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '방촌동', code: '704'),
            SubRegion(name: '각산동', code: '5580'),
            SubRegion(name: '봉무동', code: '5598'),
            SubRegion(name: '불로.봉무동', code: '701'),
            SubRegion(name: '동촌동', code: '703'),
            SubRegion(name: '동호동', code: '5592'),
            SubRegion(name: '둔산동', code: '5593'),
            SubRegion(name: '도동', code: '5589'),
            SubRegion(name: '금강동', code: '5583'),
            SubRegion(name: '괴전동', code: '5582'),
            SubRegion(name: '검사동', code: '5581'),
            SubRegion(name: '내곡동', code: '5584'),
            SubRegion(name: '내동', code: '5585'),
            SubRegion(name: '능성동', code: '5586'),
            SubRegion(name: '대림동', code: '5587'),
            SubRegion(name: '덕곡동', code: '5588'),
            SubRegion(name: '도학동', code: '5590'),
            SubRegion(name: '동내동', code: '5591'),
            SubRegion(name: '매여동', code: '5594'),
            SubRegion(name: '미곡동', code: '5595'),
            SubRegion(name: '미대동', code: '5596'),
            SubRegion(name: '백안동', code: '5597'),
            SubRegion(name: '부동', code: '5599'),
            SubRegion(name: '불로동', code: '5600'),
            SubRegion(name: '사복동', code: '5601'),
            SubRegion(name: '상매동', code: '5602'),
            SubRegion(name: '서호동', code: '5603'),
            SubRegion(name: '공산동', code: '709'),
          ],
        ),
        Gu(
          name: '남구',
          code: 'namgu',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '대명동', code: '5563'),
            SubRegion(name: '이천동', code: '729'),
            SubRegion(name: '봉덕동', code: '5564'),
            SubRegion(name: '대명1동', code: '733'),
            SubRegion(name: '대명2동', code: '734'),
            SubRegion(name: '대명3동', code: '735'),
            SubRegion(name: '대명4동', code: '736'),
            SubRegion(name: '대명5동', code: '737'),
            SubRegion(name: '대명6동', code: '738'),
            SubRegion(name: '대명9동', code: '739'),
            SubRegion(name: '대명10동', code: '740'),
            SubRegion(name: '대명11동', code: '741'),
            SubRegion(name: '봉덕1동', code: '730'),
            SubRegion(name: '봉덕2동', code: '731'),
            SubRegion(name: '봉덕3동', code: '732'),
          ],
        ),
        Gu(
          name: '군위군',
          code: 'gunwi',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '군위읍', code: '3327'),
            SubRegion(name: '소보면', code: '3328'),
            SubRegion(name: '효령면', code: '3329'),
            SubRegion(name: '부계면', code: '3330'),
            SubRegion(name: '우보면', code: '3331'),
            SubRegion(name: '의흥면', code: '3332'),
            SubRegion(name: '산성면', code: '3333'),
            SubRegion(name: '삼국유사면', code: '3334'),
          ],
        ),
      ],
    ),
    Region(
      name: '경상남도',
      code: 'gyeongnam',
      gus: [
        Gu(
          name: '함양군',
          code: 'hamyang',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '유림면', code: '3772'),
          ],
        ),
      ],
    ),
    Region(
      name: '강원특별자치도',
      code: 'gangwon',
      gus: [
        Gu(
          name: '동해시',
          code: 'donghae',
          dongs: [
            SubRegion(name: '선택 안함 (전체 동)', code: 'all'),
            SubRegion(name: '대구동', code: '4293'),
          ],
        ),
      ],
    ),
  ];

  static SubRegion? findSubRegionByName(String regionName, String subRegionName) {
    for (var region in regions) {
      if (region.name == regionName) {
        return region.subRegions?.firstWhere(
          (sub) => sub.name == subRegionName,
          orElse: () => SubRegion(name: '', code: ''),
        );
      }
    }
    return null;
  }
} 